---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Требуется пагинация
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - В каталоге должно отображаться название, рейтинг, цена со скидкой и без нее
  - На странице товара должно выводиться название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге, после добавления товара в карзину
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна храниться в сессии браузера
non-functional:
  - Сайт нужно разработать с учетом удобства использования 
  - Сайт нужно оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Интерфейс интернет-магазина должен быть удобным на мобильных устройствах (адаптивная верстка)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть совместим с последними версиями браузеров
implicit:
  - При переходе между страницами сайта не происходит перезагрузки страницы
  - Сайт должен предоставлять пользователю обратную связь, например, подтверждение добавления товара в корзину
  - Пользователь должен оставить контактные данные для того чтобы получить свой заказ
  - При сортировке по цене должна учитываться цена со скидкой
  - Протокол HTTPS
  - Пользователь не должен иметь возможности редактировать, удалять и добавлять новые товары в магазин
  - У пользователя не должно быть доступа к чужим корзинам
  - В фильтр товаров по цене нельзя вписать невалидное значение
